import assert from "node:assert/strict";
import { createRequire } from "node:module";
import path from "node:path";

const baseURL=(process.env.ZLG_REVIEW_URL||"").replace(/\/$/,"");
if(!baseURL) throw new Error("ZLG_REVIEW_URL is required");
const runtime=process.env.ZLG_PLAYWRIGHT_HOME;if(!runtime) throw new Error("ZLG_PLAYWRIGHT_HOME is required");
const require=createRequire(import.meta.url);const {chromium}=require(path.join(runtime,"playwright","index.js"));
const checks=[];const check=(name,pass,detail="")=>{checks.push({name,pass,detail});assert.equal(pass,true,`${name}: ${detail}`);};
const home=await fetch(`${baseURL}/`,{headers:{"user-agent":"node-fetch-zlg-review"}});const homeHtml=await home.text();
check("node home GET 200",home.status===200,String(home.status));check("server HTML readable",["ZLG","Physical AI","搜索","zlg-review-source-version"].every((text)=>homeHtml.includes(text)));check("review headers",home.headers.get("x-zlg-review")==="true"&&home.headers.get("x-zlg-review-production-deploy")==="6ab13e2d0dcd7f64cb3a69bf");
const apiGet=await fetch(`${baseURL}/api/product-search?query=${encodeURIComponent("清洁")}`);const apiGetJson=await apiGet.json();check("search GET 200 real data",apiGet.status===200&&apiGetJson.provider==="zlg_index"&&apiGetJson.products.length>0);
const apiPost=await fetch(`${baseURL}/api/product-search`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({query:"warehouse AMR"})});const apiPostJson=await apiPost.json();check("search POST 200 real data",apiPost.status===200&&apiPostJson.provider==="zlg_index");
const product=await fetch(`${baseURL}/products/karcher-kira-b-50`);check("product GET 200",product.status===200&&/KIRA B 50/i.test(await product.text()));
const assetMatch=homeHtml.match(/(?:src|href)="(\/_next\/[^"?]+\.(?:js|css))"/);assert.ok(assetMatch,"Expected a Next.js asset in the homepage HTML");const asset=await fetch(`${baseURL}${assetMatch[1]}`);check("static asset GET 200",asset.status===200,`${asset.status} ${assetMatch[1]}`);
const missing=await fetch(`${baseURL}/products/not-a-real-zlg-product`);check("invalid product 404",missing.status===404,String(missing.status));
const robots=await fetch(`${baseURL}/robots.txt`);check("robots allows reading",robots.status===200&&/Allow: \//.test(await robots.text()));
const blocked=await fetch(`${baseURL}/api/not-a-write`,{method:"POST",headers:{"content-type":"application/json"},body:"{}"});check("non-search write blocked",blocked.status===405,String(blocked.status));
const browser=await chromium.launch({headless:true,executablePath:"C:/Program Files/Google/Chrome/Application/chrome.exe"});const page=await browser.newPage({viewport:{width:1366,height:900}});
await page.goto(baseURL,{waitUntil:"networkidle"});check("browser homepage",(await page.title()).includes("ZLG")&&(await page.locator("body").innerText()).includes("Physical AI"));
const initialProducts=await page.locator('a[href^="/products/"]').evaluateAll((links)=>[...new Set(links.map((link)=>link.getAttribute("href")))].length);check("20 default products",initialProducts===20,String(initialProducts));
const loadMore=page.getByRole("button",{name:/加载更多产品|Load more products/i});await loadMore.click();await page.waitForTimeout(500);const loadedProducts=await page.locator('a[href^="/products/"]').evaluateAll((links)=>[...new Set(links.map((link)=>link.getAttribute("href")))].length);check("load more",loadedProducts>20,String(loadedProducts));
for(const query of ["酒店","清洁","warehouse AMR","安全","CRM software"]){await page.goto(baseURL,{waitUntil:"networkidle"});await page.locator("#global-product-search").fill(query);const responsePromise=page.waitForResponse((response)=>response.url().includes("/api/product-search")&&response.request().method()==="POST");await page.locator("form.search-instrument").evaluate((form)=>form.requestSubmit());const response=await responsePromise;await page.getByRole("button",{name:/AI 搜索|AI Search/i}).waitFor();await page.waitForTimeout(250);check(`browser search ${query}`,response.status()===200&&(await page.locator("body").innerText()).includes(query),String(response.status()));}
await page.goto(baseURL,{waitUntil:"networkidle"});await page.locator("#global-product-search").fill("清洁");const countryResponse=page.waitForResponse((response)=>response.url().includes("/api/product-search")&&response.request().method()==="POST");await page.locator("form.search-instrument").evaluate((form)=>form.requestSubmit());await countryResponse;await page.getByRole("button",{name:/AI 搜索|AI Search/i}).waitFor();const countryButton=page.getByRole("button",{name:/中国/}).first();check("country filter available",await countryButton.isVisible());await countryButton.click();await page.waitForTimeout(200);check("country filter functional",(await page.locator('a[href^="/products/"]').count())>0);
await browser.close();console.log(JSON.stringify({passed:checks.length,checks,productGraph:{productCount:apiGetJson.indexStats.productCount,familyCount:apiGetJson.indexStats.familyCount,provider:apiGetJson.provider}},null,2));
